# Generated by Django 4.1.5 on 2023-01-22 18:57

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[main_app.validators.ValidateFileMaxSizeInMB(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='main_app.pet', validators=[main_app.validators.atleastOnePet])),
            ],
        ),
    ]
