# Generated by Django 4.2.3 on 2023-07-05 23:13

import common.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[common.validator.only_letters_validator])),
                ('last_name', models.CharField(max_length=100, validators=[common.validator.only_letters_validator])),
                ('age', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
